# Generated by Django 5.0 on 2023-07-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=100, verbose_name="职业颜色")),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="职业名字"),
                ),
                (
                    "Hp",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="生命值"
                    ),
                ),
                (
                    "Mp",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="魔法值"
                    ),
                ),
                ("Level", models.IntegerField(verbose_name="等级")),
                (
                    "Damage",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="伤害值"
                    ),
                ),
                (
                    "Defence",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="防御值"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="名字"),
                ),
                (
                    "Hp",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="生命值"
                    ),
                ),
                (
                    "Mp",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="魔法值"
                    ),
                ),
                ("Level", models.IntegerField(verbose_name="等级")),
                (
                    "Damage",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="伤害值"
                    ),
                ),
                (
                    "Defence",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="防御值"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="army.role"
                    ),
                ),
            ],
        ),
    ]
