# Generated by Django 5.0 on 2023-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_books_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
